### ISSUE TITLE
how can I use SearchFilter?

### ISSUE THREAD

**Issue by chobijaeyu** [manjitkumar/drf-url-filters#37]
Good day

How to use one parameter to search multiple search terms?

![スクリーンショット 2019-08-16 14 08 51](https://user-images.githubusercontent.com/25117318/63144792-83476180-c02f-11e9-99d1-1debea26af55.png)

as drf document said:
`http://example.com/api/customers?search=00001`
not working.

But 
`http://example.com/api/customers?phone =00001`
`http://example.com/api/customers?cardid =00001`
working fine.

what is I missing?

thanks for your time.

**Comment by manjitkumar** [comment]
@chobijaeyu 
I think what you want to do is use `SearchFilter` as one of your `filter_backends`. 

i.e `filter_backends = [filters.SearchFilter]` 

```python
from rest_framework import filters

class UserListView(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['username', 'email']
```

Let me know if this helps!

**Comment by chobijaeyu** [comment]
Appreciate your help.
fixed my problem.
