### ISSUE TITLE
Don't provide absolute specifications for install_requires

### ISSUE THREAD

**Issue by pydanny** [manjitkumar/drf-url-filters#6]
``` python
    install_requires=[
        'Django==1.8.11',
        'djangorestframework==3.3.3',
        'voluptuous==0.8.10',
    ],
```
If I run Django 1.9.5, this overwrites it. Instead, maybe do this:

``` python
    install_requires=[
        'Django>=1.8.11',
        'djangorestframework>=3.3.3',
        'voluptuous>=0.8.10',
    ],
```

**Comment by manjitkumar** [comment]
Yes, We should do that. I will make a patch for the same. Thank you for pointing it out.

**Comment by manjitkumar** [comment]
Made a patch for the reported issue. Please close the issue if this merge #7 solves the issue.
https://github.com/manjitkumar/drf-url-filters/pull/7
